--DROP TABLE bill;
--DROP TABLE billitem;

CREATE TABLE bill
( 
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  userhash VARCHAR2(255) NOT NULL ,
  creationdate TIMESTAMP WITH TIME ZONE DEFAULT SYSDATE  NOT NULL,
  paymentmethod VARCHAR2(255) NOT NULL, 
  confirmationdate TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (id)
);
CREATE INDEX bill_userhash_idx ON bill (userhash);

CREATE TABLE billitem
( 
 id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  bill_id NUMBER NOT NULL,
  amount NUMBER NOT NULL,
  producthash VARCHAR2(255) NOT NULL,
  price NUMBER NOT NULL,
  discount NUMBER,
  PRIMARY KEY (id),
  FOREIGN KEY (bill_id)
        REFERENCES BILL(ID)
        ON DELETE CASCADE
);

COMMIT;

------------------------------
-- TEST DATA
DELETE FROM BILL;
DELETE FROM BILLITEM;

INSERT INTO BILL (userhash, paymentmethod)
VALUES
('user111', 'method1');
INSERT INTO BILL (userhash, paymentmethod)
VALUES
('user222', 'method1');
INSERT INTO BILL (userhash, paymentmethod)
VALUES
('user333', 'method3');


INSERT INTO BILLITEM (bill_id, amount, producthash, price)
VALUES
(
    (SELECT id from bill where userhash = 'user111'),
    1,
    'product123',
    5500
);

INSERT INTO BILLITEM (bill_id, amount, producthash, price)
VALUES
(
    (SELECT id from bill where userhash = 'user111'),
    2,
    'product456',
    10500
);

INSERT INTO BILLITEM (bill_id, amount, producthash, price)
VALUES
(
    (SELECT id from bill where userhash = 'user111'),
    10,
    'product789',
    2400
);

INSERT INTO BILLITEM (bill_id, amount, producthash, price)
VALUES
(
    (SELECT id from bill where userhash = 'user333'),
    20,
    'product1011',
    23000
);

--
--select * from bill; 
--select * from billitem;
