version: '3'

services:
  oracle-db:
    build: ./oracle-db/
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-db/data:/opt/oracle/oradata
  users-ws:
    build: ./ws-users/
    depends_on:
      - oracle-db
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8008:8009"
    volumes:
      - ./ws-users/wildfly-logs:/opt/jboss/wildfly/standalone/log